const express = require('express');
const fs = require('fs');
const path = require('path');
const pino = require("pino");
const {
    default: makeWASocket,
    useMultiFileAuthState,
    delay,
    makeCacheableSignalKeyStore,
    Browsers
} = require("@whiskeysockets/baileys");
const { v4: uuidv4 } = require('uuid');

const router = express.Router();

// Utility functions
function generateId() {
    return Math.random().toString(36).substring(2, 15);
}

function removeFile(filePath) {
    if (!fs.existsSync(filePath)) return false;
    fs.rmSync(filePath, { recursive: true, force: true });
    return true;
}

const activeSessions = new Map();

// GET endpoint for pairing codes
router.get('/code', async (req, res) => {
    const { number } = req.query;
    
    if (!number) {
        return res.status(400).json({ error: 'Phone number required' });
    }

    const sessionId = generateId();
    const tempDir = path.join(__dirname, 'temp', sessionId);
    fs.mkdirSync(tempDir, { recursive: true });

    try {
        const { state, saveCreds } = await useMultiFileAuthState(tempDir);

        const sock = makeWASocket({
            auth: {
                creds: state.creds,
                keys: makeCacheableSignalKeyStore(state.keys, pino({ level: "fatal" })),
            },
            printQRInTerminal: true, // Keep this for debugging
            logger: pino({ level: "fatal" }),
            browser: Browsers.macOS("Safari")
        });

        sock.ev.on('creds.update', saveCreds);

        sock.ev.on("connection.update", async (update) => {
            const { connection, lastDisconnect } = update;

            if (connection === "open") {
                console.log('✅ Connected successfully');
                
                await delay(3000); // Wait for session to be fully ready

                const credsPath = path.join(tempDir, 'creds.json');
                if (fs.existsSync(credsPath)) {
                    try {
                        const sessionData = fs.readFileSync(credsPath, 'utf8');
                        const base64Session = Buffer.from(sessionData).toString('base64');
                        const infinitySession = "INFINITY_" + base64Session;

                        const message = `
🔐 *YOUR WHATSAPP SESSION ID* - INFINITE-XMD

*Session ID:*
\`\`\`
${infinitySession}
\`\`\`

*Generated:* ${new Date().toLocaleString()}
*Keep this safe!* Anyone with this session can access your WhatsApp.

💻 Generated by Bevan Society Session Server
                        `;

                        await sock.sendMessage(sock.user.id, { text: message });
                        console.log('✅ Session sent to user');

                    } catch (error) {
                        console.error('Session processing error:', error);
                    }
                }

                // Cleanup
                await delay(1000);
                await sock.ws.close();
                removeFile(tempDir);
                activeSessions.delete(sessionId);
            }
            
            else if (connection === "close") {
                console.log('❌ Connection closed');
                removeFile(tempDir);
                activeSessions.delete(sessionId);
            }
        });

        // Request pairing code
        if (!sock.authState.creds.registered) {
            await delay(2000);
            const cleanNumber = number.replace(/[^0-9]/g, '');
            
            try {
                const pairingCode = await sock.requestPairingCode(cleanNumber);
                console.log('📋 Pairing code generated:', pairingCode);
                
                activeSessions.set(sessionId, { sock, tempDir, createdAt: Date.now() });
                
                res.json({ 
                    success: true, 
                    code: pairingCode,
                    sessionId: sessionId,
                    message: 'Pairing code generated successfully'
                });

            } catch (error) {
                console.error('Pairing code error:', error);
                res.status(500).json({ 
                    error: 'Failed to generate pairing code',
                    details: error.message 
                });
            }
        }

    } catch (error) {
        console.error('Pairing error:', error);
        removeFile(tempDir);
        res.status(500).json({ 
            error: 'Failed to generate pairing code',
            details: error.message 
        });
    }
});

// GET endpoint for QR code
router.get('/qr', async (req, res) => {
    const sessionId = generateId();
    const tempDir = path.join(__dirname, 'temp', sessionId);
    fs.mkdirSync(tempDir, { recursive: true });

    try {
        const { state, saveCreds } = await useMultiFileAuthState(tempDir);

        const sock = makeWASocket({
            auth: {
                creds: state.creds,
                keys: makeCacheableSignalKeyStore(state.keys, pino({ level: "fatal" })),
            },
            printQRInTerminal: true, // Keep for debugging
            logger: pino({ level: "fatal" }),
            browser: Browsers.macOS("Safari")
        });

        sock.ev.on('creds.update', saveCreds);

        sock.ev.on("connection.update", async (update) => {
            const { connection, lastDisconnect, qr } = update;

            if (qr) {
                console.log('📱 QR code generated');
                res.json({ 
                    success: true, 
                    qr: qr,
                    sessionId: sessionId 
                });
            }

            if (connection === "open") {
                console.log('✅ Connected via QR');
                
                await delay(3000);

                const credsPath = path.join(tempDir, 'creds.json');
                if (fs.existsSync(credsPath)) {
                    try {
                        const sessionData = fs.readFileSync(credsPath, 'utf8');
                        const base64Session = Buffer.from(sessionData).toString('base64');
                        const infinitySession = "INFINITY_" + base64Session;

                        const userNumber = sock.user.id;
                        const message = `
🔐 *YOUR WHATSAPP SESSION ID* - INFINITE-XMD

*Session ID:*
\`\`\`
${infinitySession}
\`\`\`

*Generated:* ${new Date().toLocaleString()}
*Keep this safe!* Anyone with this session can access your WhatsApp.

💻 Generated by Bevan Society Session Server
                        `;

                        await sock.sendMessage(userNumber, { text: message });
                        console.log('✅ Session sent via QR');

                    } catch (error) {
                        console.error('QR session error:', error);
                    }
                }

                await delay(1000);
                await sock.ws.close();
                removeFile(tempDir);
                activeSessions.delete(sessionId);
            }
            
            else if (connection === "close") {
                console.log('❌ QR connection closed');
                removeFile(tempDir);
                activeSessions.delete(sessionId);
            }
        });

        activeSessions.set(sessionId, { sock, tempDir, createdAt: Date.now() });

        // Timeout if no QR generated within 30 seconds
        setTimeout(() => {
            if (activeSessions.has(sessionId)) {
                const session = activeSessions.get(sessionId);
                if (session.sock) session.sock.ws.close();
                removeFile(tempDir);
                activeSessions.delete(sessionId);
                
                if (!res.headersSent) {
                    res.status(408).json({ error: 'QR generation timeout' });
                }
            }
        }, 30000);

    } catch (error) {
        console.error('QR generation error:', error);
        removeFile(tempDir);
        res.status(500).json({ 
            error: 'Failed to generate QR code',
            details: error.message 
        });
    }
});

// Cleanup every 5 minutes
setInterval(() => {
    const now = Date.now();
    for (const [sessionId, session] of activeSessions.entries()) {
        if (now - session.createdAt > 300000) {
            if (session.sock) session.sock.ws.close();
            removeFile(session.tempDir);
            activeSessions.delete(sessionId);
        }
    }
}, 60000);

module.exports = router;
